# CMake generated Testfile for 
# Source directory: /home/runner/work/evo/evo/tests
# Build directory: /home/runner/work/evo/evo/build-search/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[evo_smoke_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_smoke_test")
set_tests_properties([=[evo_smoke_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;3;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_lifecycle_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_lifecycle_test")
set_tests_properties([=[evo_lifecycle_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;7;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_population_storage_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_population_storage_test")
set_tests_properties([=[evo_population_storage_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;12;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_population_recycling_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_population_recycling_test")
set_tests_properties([=[evo_population_recycling_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;17;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_rng_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_rng_test")
set_tests_properties([=[evo_rng_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;22;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_population_initialization_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_population_initialization_test")
set_tests_properties([=[evo_population_initialization_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;27;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_population_evaluation_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_population_evaluation_test")
set_tests_properties([=[evo_population_evaluation_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;32;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_evaluation_workers_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_evaluation_workers_test")
set_tests_properties([=[evo_evaluation_workers_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;37;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_fitness_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_fitness_test")
set_tests_properties([=[evo_fitness_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;42;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_selection_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_selection_test")
set_tests_properties([=[evo_selection_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;47;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_crossover_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_crossover_test")
set_tests_properties([=[evo_crossover_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;52;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_mutation_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_mutation_test")
set_tests_properties([=[evo_mutation_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;57;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_adaptive_mutation_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_adaptive_mutation_test")
set_tests_properties([=[evo_adaptive_mutation_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;62;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_child_population_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_child_population_test")
set_tests_properties([=[evo_child_population_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;67;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_parent_pair_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_parent_pair_test")
set_tests_properties([=[evo_parent_pair_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;72;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_child_pair_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_child_pair_test")
set_tests_properties([=[evo_child_pair_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;77;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_child_tail_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_child_tail_test")
set_tests_properties([=[evo_child_tail_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;82;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_elite_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_elite_test")
set_tests_properties([=[evo_elite_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;87;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_child_evaluation_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_child_evaluation_test")
set_tests_properties([=[evo_child_evaluation_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;92;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_generation_advancement_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_generation_advancement_test")
set_tests_properties([=[evo_generation_advancement_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;97;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_bounded_run_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_bounded_run_test")
set_tests_properties([=[evo_bounded_run_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;102;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_statistics_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_statistics_test")
set_tests_properties([=[evo_statistics_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;107;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_diversity_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_diversity_test")
set_tests_properties([=[evo_diversity_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;112;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_observer_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_observer_test")
set_tests_properties([=[evo_observer_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;117;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_application_stop_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_application_stop_test")
set_tests_properties([=[evo_application_stop_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;121;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_stopping_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_stopping_test")
set_tests_properties([=[evo_stopping_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;125;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_checkpoint_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_checkpoint_test")
set_tests_properties([=[evo_checkpoint_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;129;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_checkpoint_fuzz_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_checkpoint_fuzz_test")
set_tests_properties([=[evo_checkpoint_fuzz_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;133;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_seed_schedule_research_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_seed_schedule_research_test")
set_tests_properties([=[evo_seed_schedule_research_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;153;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_seed_schedule_experiment]=] "/home/runner/work/evo/evo/build-search/tests/evo_seed_schedule_experiment")
set_tests_properties([=[evo_seed_schedule_experiment]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;163;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_project_ingestion_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_project_ingestion_test")
set_tests_properties([=[evo_project_ingestion_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;181;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_project_analysis_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_project_analysis_test")
set_tests_properties([=[evo_project_analysis_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;199;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_project_recipe_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_project_recipe_test")
set_tests_properties([=[evo_project_recipe_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;217;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_project_transformation_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_project_transformation_test")
set_tests_properties([=[evo_project_transformation_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;235;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_project_candidate_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_project_candidate_test")
set_tests_properties([=[evo_project_candidate_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;251;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_project_assurance_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_project_assurance_test")
set_tests_properties([=[evo_project_assurance_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;267;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_project_measurement_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_project_measurement_test")
set_tests_properties([=[evo_project_measurement_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;283;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_project_search_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_project_search_test")
set_tests_properties([=[evo_project_search_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;299;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_secure_erasure_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_secure_erasure_test")
set_tests_properties([=[evo_secure_erasure_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;317;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
add_test([=[evo_allocation_failure_test]=] "/home/runner/work/evo/evo/build-search/tests/evo_allocation_failure_test")
set_tests_properties([=[evo_allocation_failure_test]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/evo/evo/tests/CMakeLists.txt;328;add_test;/home/runner/work/evo/evo/tests/CMakeLists.txt;0;")
